module.exports = {
  black: '#1E1E1E',
  blue: '#3369F3',
  'dark-blue': '#3369F3',
  'light-blue': '#E4EDFD',
  'light-gray': '#FBFBFB',
  'medium-gray': '#EAEAEA',
  'btn-gray': 'F5F5F5',
  'search-gray': '#EFEFEF',
  bg: '#EFEFEF',
  gray: '#999',
  white: '#FFFFFF',
  red: '#FF0000',
  font_base: '16',
  font_base_px: '$font_base * 1px',
};
