export default
[
  {
    id: '1',
    href: '/chat.html',
    name: 'Андрей',
    imgSrc: '',
    datetime: '10:49',
    lastMessageText: 'Изображение',
    countNewMessage: 2,
  },
  {
    id: '2',
    href: '/chat.html',
    name: 'Киноклуб',
    imgSrc: '',
    datetime: '12:00',
    lastMessageText: 'Изображение',
    countNewMessage: 0,
  },
  {
    id: '3',
    href: '/chat.html',
    name: 'Илья',
    imgSrc: '',
    datetime: '15:12',
    lastMessageText: 'Изображение',
    countNewMessage: 4,
  },
  {
    id: '4',
    href: '/chat.html',
    name: 'Вадим',
    imgSrc: '',
    datetime: 'Пт',
    lastMessageText: 'Изображение',
    countNewMessage: 0,
  },
  {
    id: '5',
    href: '/chat.html',
    name: 'тет-а-теты',
    imgSrc: '',
    datetime: 'Ср',
    lastMessageText: 'Изображение',
    countNewMessage: 0,
  },
  {
    id: '6',
    href: '/chat.html',
    name: '1, 2, 3',
    imgSrc: '',
    datetime: 'Пн',
    lastMessageText: 'Изображение',
    countNewMessage: 0,
  },
  {
    id: '7',
    href: '/chat.html',
    name: 'Design Destroyer',
    imgSrc: '',
    datetime: 'Пн',
    lastMessageText: 'Изображение',
    countNewMessage: 0,
  },
  {
    id: '8',
    href: '/chat.html',
    name: 'Day.',
    imgSrc: '',
    datetime: '1 Мая 2020',
    lastMessageText: 'Изображение',
    countNewMessage: 0,
  },
  {
    id: '9',
    href: '/chat.html',
    name: 'Стас Рогозин',
    imgSrc: '',
    datetime: '12 Апр 2020',
    lastMessageText: 'Изображение',
    countNewMessage: 0,
  },
];
